function delta_dq = delta_dq_(in1,in2,t,in4)
%DELTA_DQ_
%    DELTA_DQ = DELTA_DQ_(IN1,IN2,T,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    28-Oct-2025 19:43:14

c_Gr_Disc = in4(19,:);
c_Gr_Slider = in4(22,:);
d_Arm1 = in4(7,:);
g = in4(23,:);
h = in1(2,:);
h_dot = in2(2,:);
i_Arm11 = in4(9,:);
i_Arm12 = in4(12,:);
i_Arm33 = in4(11,:);
i_Disc11 = in4(14,:);
i_Disc22 = in4(15,:);
k_Gr_Slider = in4(20,:);
l = in1(4,:);
l_dot = in2(4,:);
m_Arm = in4(6,:);
m_Disc = in4(13,:);
m_Slider = in4(3,:);
phi_dot = in2(5,:);
psi_dot = in2(1,:);
rho0 = in4(21,:);
theta = in1(3,:);
theta_dot = in2(3,:);
mt1 = [-c_Gr_Disc.*psi_dot-c_Gr_Disc.*phi_dot.*sin(theta)+i_Arm12.*theta_dot.^2.*cos(theta)-i_Disc11.*phi_dot.*theta_dot.*cos(theta)-i_Arm11.*psi_dot.*theta_dot.*sin(theta.*2.0)+i_Arm33.*psi_dot.*theta_dot.*sin(theta.*2.0)-i_Disc11.*psi_dot.*theta_dot.*sin(theta.*2.0)+i_Disc22.*psi_dot.*theta_dot.*sin(theta.*2.0)-l.*l_dot.*m_Disc.*psi_dot.*cos(theta).^2.*2.0+l.^2.*m_Disc.*psi_dot.*theta_dot.*sin(theta.*2.0);-c_Gr_Slider.*h_dot-h.*k_Gr_Slider-g.*m_Arm-g.*m_Disc-g.*m_Slider+k_Gr_Slider.*rho0+l_dot.*m_Disc.*theta_dot.*cos(theta).*2.0-d_Arm1.*m_Arm.*theta_dot.^2.*sin(theta)-l.*m_Disc.*theta_dot.^2.*sin(theta)];
mt2 = [-c_Gr_Disc.*theta_dot+(i_Arm11.*psi_dot.^2.*sin(theta.*2.0))./2.0-(i_Arm33.*psi_dot.^2.*sin(theta.*2.0))./2.0+(i_Disc11.*psi_dot.^2.*sin(theta.*2.0))./2.0-(i_Disc22.*psi_dot.^2.*sin(theta.*2.0))./2.0-l.*l_dot.*m_Disc.*theta_dot.*2.0+d_Arm1.*g.*m_Arm.*cos(theta)+g.*l.*m_Disc.*cos(theta)+i_Disc11.*phi_dot.*psi_dot.*cos(theta)-(l.^2.*m_Disc.*psi_dot.^2.*sin(theta.*2.0))./2.0;l.*m_Disc.*theta_dot.^2+g.*m_Disc.*sin(theta)+l.*m_Disc.*psi_dot.^2.*cos(theta).^2;-c_Gr_Disc.*phi_dot-c_Gr_Disc.*psi_dot.*sin(theta)-i_Disc11.*psi_dot.*theta_dot.*cos(theta)];
delta_dq = [mt1;mt2];
end
