function delta_dq_orth = delta_dq_orth_(in1,in2,t,in4)
%DELTA_DQ_ORTH_
%    DELTA_DQ_ORTH = DELTA_DQ_ORTH_(IN1,IN2,T,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    28-Oct-2025 19:43:14

c_Gr_Disc = in4(19,:);
c_Gr_Slider = in4(22,:);
d_Arm1 = in4(7,:);
d_Arm2 = in4(8,:);
g = in4(23,:);
h = in1(2,:);
h_dot = in2(2,:);
i_Arm11 = in4(9,:);
i_Arm12 = in4(12,:);
i_Arm22 = in4(10,:);
i_Arm33 = in4(11,:);
i_Disc11 = in4(14,:);
i_Disc22 = in4(15,:);
k_Gr_Slider = in4(20,:);
l = in1(4,:);
l_dot = in2(4,:);
m_Arm = in4(6,:);
m_Disc = in4(13,:);
m_Slider = in4(3,:);
phi = in1(5,:);
phi_dot = in2(5,:);
psi_dot = in2(1,:);
rho0 = in4(21,:);
theta = in1(3,:);
theta_dot = in2(3,:);
mt1 = [0.0;0.0;0.0;0.0;-sin(theta).*(c_Gr_Slider.*h_dot+g.*m_Slider+k_Gr_Slider.*(h-rho0))+d_Arm1.*m_Arm.*theta_dot.^2+g.*m_Arm.*sin(theta)+d_Arm1.*m_Arm.*psi_dot.^2.*cos(theta).^2;d_Arm2.*m_Arm.*psi_dot.^2+d_Arm1.*m_Arm.*psi_dot.*theta_dot.*sin(theta).*2.0;cos(theta).*(c_Gr_Slider.*h_dot+g.*m_Slider+k_Gr_Slider.*(h-rho0))-g.*m_Arm.*cos(theta)+d_Arm1.*m_Arm.*psi_dot.^2.*cos(theta).*sin(theta);i_Arm12.*psi_dot.^2.*sin(theta.*2.0).*(-1.0./2.0)-d_Arm2.*g.*m_Arm.*cos(theta)+i_Arm11.*psi_dot.*theta_dot.*cos(theta)+i_Arm22.*psi_dot.*theta_dot.*cos(theta)-i_Arm33.*psi_dot.*theta_dot.*cos(theta);-i_Arm12.*psi_dot.^2+i_Arm12.*theta_dot.^2+i_Arm12.*psi_dot.^2.*cos(theta).^2-d_Arm2.*g.*m_Arm.*sin(theta)-i_Arm11.*psi_dot.*theta_dot.*sin(theta)+i_Arm22.*psi_dot.*theta_dot.*sin(theta)+i_Arm33.*psi_dot.*theta_dot.*sin(theta)];
mt2 = [-(l.*cos(theta).^2.*sin(phi)+l.*sin(phi).*sin(theta).^2).*((i_Arm11.*psi_dot.^2.*sin(theta.*2.0))./2.0-(i_Arm33.*psi_dot.^2.*sin(theta.*2.0))./2.0+d_Arm1.*g.*m_Arm.*cos(theta))-cos(theta).*sin(phi).*(c_Gr_Slider.*h_dot+g.*m_Slider+k_Gr_Slider.*(h-rho0))-l_dot.*m_Disc.*theta_dot.*sin(phi).*2.0+g.*m_Disc.*cos(theta).*sin(phi)-l_dot.*m_Disc.*psi_dot.*cos(phi).*cos(theta).*2.0-l.*m_Disc.*psi_dot.^2.*cos(theta).*sin(phi).*sin(theta)+l.*m_Disc.*psi_dot.*theta_dot.*cos(phi).*sin(theta).*2.0];
mt3 = [(l.*cos(phi).*cos(theta).^2+l.*cos(phi).*sin(theta).^2).*((i_Arm11.*psi_dot.^2.*sin(theta.*2.0))./2.0-(i_Arm33.*psi_dot.^2.*sin(theta.*2.0))./2.0+d_Arm1.*g.*m_Arm.*cos(theta))+cos(phi).*cos(theta).*(c_Gr_Slider.*h_dot+g.*m_Slider+k_Gr_Slider.*(h-rho0))+l_dot.*m_Disc.*theta_dot.*cos(phi).*2.0-g.*m_Disc.*cos(phi).*cos(theta)-l_dot.*m_Disc.*psi_dot.*cos(theta).*sin(phi).*2.0+l.*m_Disc.*psi_dot.^2.*cos(phi).*cos(theta).*sin(theta)+l.*m_Disc.*psi_dot.*theta_dot.*sin(phi).*sin(theta).*2.0;-c_Gr_Disc.*theta_dot-cos(phi).*((i_Arm11.*psi_dot.^2.*sin(theta.*2.0))./2.0-(i_Arm33.*psi_dot.^2.*sin(theta.*2.0))./2.0+d_Arm1.*g.*m_Arm.*cos(theta))+(i_Disc11.*psi_dot.^2.*sin(theta.*2.0))./2.0-(i_Disc22.*psi_dot.^2.*sin(theta.*2.0))./2.0+i_Disc11.*phi_dot.*psi_dot.*cos(theta)];
mt4 = [-sin(phi).*((i_Arm11.*psi_dot.^2.*sin(theta.*2.0))./2.0-(i_Arm33.*psi_dot.^2.*sin(theta.*2.0))./2.0+d_Arm1.*g.*m_Arm.*cos(theta))-c_Gr_Disc.*psi_dot.*cos(theta)-i_Disc11.*phi_dot.*theta_dot-i_Disc11.*psi_dot.*theta_dot.*sin(theta)+i_Disc22.*psi_dot.*theta_dot.*sin(theta).*2.0];
delta_dq_orth = [mt1;mt2;mt3;mt4];
end
