function FC_dq_orth_epsilon = FC_dq_orth_epsilon_(in1,t,in3)
%FC_dq_orth_epsilon_
%    FC_dq_orth_epsilon = FC_dq_orth_epsilon_(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    28-Oct-2025 19:43:14

R = in3(1,:);
l = in1(4,:);
phi = in1(5,:);
theta = in1(3,:);
mt1 = [1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,cos(theta),0.0,sin(theta),0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sin(theta).*-2.0,0.0,cos(theta).*2.0,0.0,0.0,-cos(theta).*sin(phi),cos(phi).*cos(theta),0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,cos(theta),sin(theta),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sin(theta).*-2.0,cos(theta).*2.0,l.*cos(phi).*cos(theta),l.*cos(theta).*sin(phi),-cos(theta).*sin(phi),cos(phi).*cos(theta),0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,-l,cos(phi),sin(phi),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0];
mt2 = [-sin(phi)-l.*(l.*cos(theta).^2.*sin(phi)+l.*sin(phi).*sin(theta).^2),cos(phi)+l.*(l.*cos(phi).*cos(theta).^2+l.*cos(phi).*sin(theta).^2),-l.*cos(phi),-l.*sin(phi),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,l.*cos(theta).^2.*sin(phi)+l.*sin(phi).*sin(theta).^2,-l.*cos(phi).*cos(theta).^2-l.*cos(phi).*sin(theta).^2,cos(phi)+1.0,sin(phi),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-sin(phi).*sin(theta),cos(phi).*sin(theta),-R.*cos(theta),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,cos(phi),sin(phi),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-cos(theta).*sin(phi),cos(phi).*cos(theta),R.*sin(theta),0.0];
FC_dq_orth_epsilon = reshape([mt1,mt2],13,16);
end
