function FC_dq_epsilon = FC_dq_epsilon_(in1,t,in3)
%FC_dq_epsilon_
%    FC_dq_epsilon = FC_dq_epsilon_(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    28-Oct-2025 19:43:14

R = in3(1,:);
l = in1(4,:);
theta = in1(3,:);
FC_dq_epsilon = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-R.*cos(theta)-l.*sin(theta),cos(theta),0.0,-R.*sin(theta)+l.*cos(theta),0.0,0.0,0.0,-R,0.0,1.0,R.*sin(theta)-l.*cos(theta),-sin(theta),0.0],[5,16]);
end
