function M_dq_orth_ddq = M_dq_orth_ddq_(in1,t,in3)
%M_dq_orth_ddq_
%    M_dq_orth_ddq = M_dq_orth_ddq_(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    28-Oct-2025 19:43:14

d_Arm1 = in3(7,:);
d_Arm2 = in3(8,:);
i_Arm11 = in3(9,:);
i_Arm12 = in3(12,:);
i_Arm22 = in3(10,:);
i_Arm33 = in3(11,:);
i_Disc22 = in3(15,:);
i_Slider33 = in3(5,:);
l = in1(4,:);
m_Arm = in3(6,:);
m_Disc = in3(13,:);
m_Slider = in3(3,:);
phi = in1(5,:);
theta = in1(3,:);
mt1 = [0.0,0.0,0.0,0.0,-d_Arm2.*m_Arm.*cos(theta),d_Arm1.*m_Arm.*cos(theta),-d_Arm2.*m_Arm.*sin(theta),-i_Arm11.*sin(theta)+i_Slider33.*sin(theta),i_Arm33.*cos(theta)-i_Slider33.*cos(theta),i_Arm12.*sin(theta).*(l.*cos(theta).^2.*sin(phi)+l.*sin(phi).*sin(theta).^2)-i_Slider33.*l.*cos(phi).*cos(theta)+l.*m_Disc.*cos(phi).*cos(theta),-i_Arm12.*sin(theta).*(l.*cos(phi).*cos(theta).^2+l.*cos(phi).*sin(theta).^2)-i_Slider33.*l.*cos(theta).*sin(phi)+l.*m_Disc.*cos(theta).*sin(phi),i_Arm12.*cos(phi).*sin(theta)+i_Slider33.*cos(theta).*sin(phi),i_Disc22.*cos(theta)-i_Slider33.*cos(phi).*cos(theta)+i_Arm12.*sin(phi).*sin(theta),0.0,0.0,0.0,0.0,-m_Arm.*sin(theta)+m_Slider.*sin(theta),0.0,m_Arm.*cos(theta)-m_Slider.*cos(theta),d_Arm2.*m_Arm.*cos(theta),d_Arm2.*m_Arm.*sin(theta)];
mt2 = [-m_Disc.*cos(theta).*sin(phi)+m_Slider.*cos(theta).*sin(phi)+d_Arm1.*m_Arm.*cos(theta).*(l.*cos(theta).^2.*sin(phi)+l.*sin(phi).*sin(theta).^2),m_Disc.*cos(phi).*cos(theta)-m_Slider.*cos(phi).*cos(theta)-d_Arm1.*m_Arm.*cos(theta).*(l.*cos(phi).*cos(theta).^2+l.*cos(phi).*sin(theta).^2),d_Arm1.*m_Arm.*cos(phi).*cos(theta),d_Arm1.*m_Arm.*cos(theta).*sin(phi),0.0,0.0,0.0,0.0,0.0,0.0,-d_Arm1.*m_Arm,i_Arm12,0.0,-i_Arm22.*(l.*cos(theta).^2.*sin(phi)+l.*sin(phi).*sin(theta).^2)+l.*m_Disc.*sin(phi),i_Arm22.*(l.*cos(phi).*cos(theta).^2+l.*cos(phi).*sin(theta).^2)-l.*m_Disc.*cos(phi),i_Disc22-i_Arm22.*cos(phi),-i_Arm22.*sin(phi),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0];
M_dq_orth_ddq = reshape([mt1,mt2],13,5);
end
