function M_dq_ddq = M_dq_ddq_(in1,t,in3)
%M_dq_ddq_
%    M_dq_ddq = M_dq_ddq_(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    28-Oct-2025 19:43:14

d_Arm1 = in3(7,:);
i_Arm11 = in3(9,:);
i_Arm12 = in3(12,:);
i_Arm22 = in3(10,:);
i_Arm33 = in3(11,:);
i_Disc11 = in3(14,:);
i_Disc22 = in3(15,:);
i_Slider33 = in3(5,:);
l = in1(4,:);
m_Arm = in3(6,:);
m_Disc = in3(13,:);
m_Slider = in3(3,:);
theta = in1(3,:);
M_dq_ddq = reshape([i_Arm11+i_Disc11+i_Slider33-i_Arm11.*cos(theta).^2+i_Arm33.*cos(theta).^2-i_Disc11.*cos(theta).^2+i_Disc22.*cos(theta).^2+l.^2.*m_Disc.*cos(theta).^2,0.0,-i_Arm12.*sin(theta),0.0,i_Disc11.*sin(theta),0.0,m_Arm+m_Disc+m_Slider,-d_Arm1.*m_Arm.*cos(theta)-l.*m_Disc.*cos(theta),-m_Disc.*sin(theta),0.0,-i_Arm12.*sin(theta),-d_Arm1.*m_Arm.*cos(theta)-l.*m_Disc.*cos(theta),i_Arm22+i_Disc22+l.^2.*m_Disc,0.0,0.0,0.0,-m_Disc.*sin(theta),0.0,m_Disc,0.0,i_Disc11.*sin(theta),0.0,0.0,0.0,i_Disc11],[5,5]);
end
