function M_V_ddq = M_V_ddq_(in1,t,in3)
%M_V_ddq_
%    M_V_ddq = M_V_ddq_(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    28-Oct-2025 19:43:14

d_Arm1 = in3(7,:);
d_Arm2 = in3(8,:);
i_Arm11 = in3(9,:);
i_Arm12 = in3(12,:);
i_Arm22 = in3(10,:);
i_Arm33 = in3(11,:);
i_Disc11 = in3(14,:);
i_Disc22 = in3(15,:);
i_Slider33 = in3(5,:);
l = in1(4,:);
m_Arm = in3(6,:);
m_Disc = in3(13,:);
m_Slider = in3(3,:);
phi = in1(5,:);
theta = in1(3,:);
M_V_ddq = reshape([0.0,0.0,0.0,0.0,0.0,i_Slider33,-d_Arm2.*m_Arm.*cos(theta),d_Arm1.*m_Arm.*cos(theta),-d_Arm2.*m_Arm.*sin(theta),-i_Arm11.*sin(theta),-i_Arm12.*sin(theta),i_Arm33.*cos(theta),0.0,l.*m_Disc.*cos(phi).*cos(theta),l.*m_Disc.*cos(theta).*sin(phi),-i_Disc11.*sin(theta),0.0,i_Disc22.*cos(theta),0.0,0.0,m_Slider,0.0,0.0,0.0,-m_Arm.*sin(theta),0.0,m_Arm.*cos(theta),d_Arm2.*m_Arm.*cos(theta),-d_Arm1.*m_Arm.*cos(theta),d_Arm2.*m_Arm.*sin(theta),-m_Disc.*sin(theta),-m_Disc.*cos(theta).*sin(phi),m_Disc.*cos(phi).*cos(theta),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-d_Arm1.*m_Arm,i_Arm12,i_Arm22,0.0,0.0,l.*m_Disc.*sin(phi),-l.*m_Disc.*cos(phi),0.0,i_Disc22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,m_Disc,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-i_Disc11,0.0,0.0],[18,5]);
end
