function V_dq = V_dq_(in1,t,in3)
%V_dq_
%    V_dq = V_dq_(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    28-Oct-2025 19:43:14

l = in1(4,:);
phi = in1(5,:);
theta = in1(3,:);
V_dq = reshape([0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,-sin(theta),0.0,cos(theta),0.0,l.*cos(phi).*cos(theta),l.*cos(theta).*sin(phi),-sin(theta),-cos(theta).*sin(phi),cos(phi).*cos(theta),0.0,0.0,1.0,0.0,0.0,0.0,-sin(theta),0.0,cos(theta),0.0,0.0,0.0,-sin(theta),-cos(theta).*sin(phi),cos(phi).*cos(theta),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,l.*cos(theta).^2.*sin(phi)+l.*sin(phi).*sin(theta).^2,-l.*cos(phi).*cos(theta).^2-l.*cos(phi).*sin(theta).^2,0.0,cos(phi),sin(phi),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,cos(theta).^2+sin(theta).^2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-cos(theta).^2-sin(theta).^2,0.0,0.0],[18,5]);
end
