function [translation,rotation] = abs_transform(in1,in2,in3,t,in5)
%ABS_TRANSFORM
%    [TRANSLATION,ROTATION] = ABS_TRANSFORM(IN1,IN2,IN3,T,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    18-Sep-2018 11:10:00

translation = [0.0;0.0;0.0];
if nargout > 1
    rotation = reshape([1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0],[3,3]);
end
